2019-07-27 18:11:43,800 ERROR: Exception on /edit_profile [GET] [in c:\projects\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\projects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\projects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\projects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\projects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\projects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\projects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\projects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\projects\microblog\app\routes.py", line 99, in edit_profile
    form=form)
  File "c:\projects\microblog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\projects\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\projects\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\projects\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\projects\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\projects\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\projects\microblog\app\templates\edit_profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\projects\microblog\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "C:\projects\microblog\app\templates\edit_profile.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "c:\projects\microblog\venv\lib\site-packages\flask_wtf\form.py", line 135, in hidden_tag
    u'\n'.join(text_type(f) for f in hidden_fields(fields or self))
  File "c:\projects\microblog\venv\lib\site-packages\flask_wtf\form.py", line 135, in <genexpr>
    u'\n'.join(text_type(f) for f in hidden_fields(fields or self))
  File "c:\projects\microblog\venv\lib\site-packages\flask_wtf\form.py", line 125, in hidden_fields
    for f in fields:
  File "c:\projects\microblog\venv\lib\site-packages\wtforms\form.py", line 57, in __iter__
    return iter(itervalues(self._fields))
AttributeError: 'EditProfileForm' object has no attribute '_fields'
2019-07-27 18:13:23,714 INFO: Microblog startup [in C:\projects\microblog\app\__init__.py:48]
2019-07-27 18:13:36,386 ERROR: Exception on /edit_profile [GET] [in c:\projects\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\projects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\projects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\projects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\projects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\projects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\projects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\projects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\projects\microblog\app\routes.py", line 89, in edit_profile
    form = EditProfileForm()
  File "c:\projects\microblog\venv\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2019-07-27 18:14:42,560 INFO: Microblog startup [in C:\projects\microblog\app\__init__.py:48]
2019-07-27 18:16:17,699 INFO: Microblog startup [in C:\projects\microblog\app\__init__.py:48]
2019-07-27 18:25:50,972 INFO: Microblog startup [in C:\projects\microblog\app\__init__.py:48]
